In [47]:
import cv2
import numpy as np

def displayImage(title,image):
    cv2.imshow(title,image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Task#1: 

Brightness Adjustment

In [ ]:
dimImage = cv2.imread('dimImage.jpg')
displayImage('Before Brightness',dimImage)

height, width, channels = dimImage.shape

for i in range(height):
    for j in range(width):
        print(dimImage[i,j])

displayImage('After Brightness',dimImage)


[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]


Task#2: Diadic Operations

Task#3: Green Screen Effect

In [42]:

greenScreenImage = cv2.imread('images.jpg')
displayImage("Green Screen Image", greenScreenImage)
backgroundImage = cv2.imread('background.jpg')
displayImage('Background Image',backgroundImage)


In [43]:
print(greenScreenImage.shape)
print(backgroundImage.shape)
backgroundImage = cv2.resize(backgroundImage, (greenScreenImage.shape[1], greenScreenImage.shape[0]))
print(greenScreenImage.shape)
print(backgroundImage.shape)



(168, 299, 3)
(168, 300, 3)
(168, 299, 3)
(168, 299, 3)


In [44]:
greenHSV = cv2.cvtColor(greenScreenImage,cv2.COLOR_BGR2HSV)

lower_green = np.array([35, 100, 100])
upper_green = np.array([85, 255, 255])

mask = cv2.inRange(greenHSV,lower_green,upper_green)
displayImage('mask',mask)

mask_inv = cv2.bitwise_not(mask)
displayImage('Mask invert',mask_inv)


In [45]:
fg_part = cv2.bitwise_and(greenScreenImage,greenScreenImage,mask=mask_inv)
displayImage('Green Screen Image part',fg_part)


bg_part = cv2.bitwise_and(backgroundImage,backgroundImage,mask=mask)
displayImage('Background Image part',bg_part)


In [46]:
final_image = cv2.add(fg_part,bg_part)
displayImage("Final Result",final_image)